image: ruby:2.4.2

stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install 

build_job:
  tags:
    - docker
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  tags:
    - docker
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  tags:
    - docker
  stage: test
  script:
    - echo 'Testing 2'

deploy_job:
  tags:
    - docker
  stage: deploy
  script:
    - echo 'Deploy'
