dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
notifications:
  slack:
    secure: iKILY0UTF4/zte+m0irwA2tqK7ayqT1WzyfnqCkvJXv7EW46ePhiGhqLhucHAhAhRdHXZupTZmR0h7kE2AH8JrB1BbpjiAH5+1jbXLPLXEf56wfNrZATamxbDiDVdIpDn/indYCcL3sbyF/6MMLPxFXdTxwLdjXVZkKCezy67GoCwTovfq4/SXUlpJy/LXWJuscMtEffcIUUwCrguiP6QeA7C45YYLbKG2lyxEsSk2NeoYzCiR+2uMHOIiMmZI3LDxg354+jSZmo5yi1yeVnEjddt2yeT4XMaNbRkBDi5ER84DP9ZST4q3Z0Kuy6XB6M3AZm5S8cjXvc27hSEy4OoJLEXS/rc5vndT+6OhbT8GcAY+TaH0Du7vqFZwIXH/xSgF7eIB5h63DfPifVrElLPg42bk6eQGuH1BOEUUEo5b++702uVCVJToPSGlsYfhvDOB9mSLZbVFAreSxJXE16zHA8jgbil95RG91BZF3xwNCFS+X15VeSaSVjvKWfBMPJSpgeZxAWJkHQmHps95MxBjl3UlNiZa5VgGAuCQkLC+nSX06aoJUnOmxog/zsD+5UX4sCtLFkxZOlGWEGa75WLZs3C/INBDDJQLZLEVF/1dPuOXQ1D7rv3PynyledNB81RPqIO6nPjgW470RrfKiRLa+WNvejEyPhtgtnWGKkyYU=
